---
title: "analisis_pib_pais"
author: "Ana Gabriela Alvarez, Sandra Lopez y Susana Meoño"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(datos)
library(ggplot2)
```

```{r}
paises <- datos::paises
glimpse(paises)
View(paises)
```

```{r}
# Obtener la tabla descendente con el PIB per cápita para los países del continente "Americas" en el año 2007.

paises_america_2007 <- paises |>
  filter(continente == "Américas" & anio == 2007)
View(paises_america_2007)
```

```{r}
# ordenar descendentemente

paises_ordenados <- arrange(paises_america_2007, desc(pib_per_capita))
View(paises_ordenados)
```

```{r}
#Hacer el gráfico de barras que represente el PIB per cápita por país.
ggplot(data = paises_ordenados) +
  geom_bar(mapping = aes(y = pais, fill = pib_per_capita))
```

```{r}
mi_paleta <- c("#0070FF","#58508D","#BC5080","#FF6361",
               "#FFA600", "#090C9B", "#FF9966", "#002147")
```


```{r}
#Agregar Titulo, subtitulo y paleta de colores
ggplot(data = paises_ordenados) +
  geom_bar(mapping = aes(y = pais, fill = pib_per_capita))+
   labs(
    title = "Ingreso per capita de los países de América ",
    subtitle = "Año 2007")+
   scale_fill_manual(values = mi_paleta)

```

